name: Extract and Release CSV

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  extract-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure Git
      run: |
       git config user.name "GitHub Actions Bot"
       git config user.email "actions@github.com"

    - name: Add upstream remote
      run: git remote add upstream https://github.com/LJPc-solutions/Nederlandse-adressen-en-postcodes.git

    - name: Fetch upstream
      run: | 
        git fetch upstream main
        git checkout upstream/main -- adressen.tar.xz provincies.tar.xz
        git add adressen.tar.xz provincies.tar.xz


    - name: Merge upstream/main into main
      run: |
       git checkout main
       git reset --hard
       git merge upstream/main --allow-unrelated-histories --no-edit || echo "No changes to merge"

    - name: Push changes
      run: |
       git push origin main

    - name: Extract CSV from adressen.tar.xz with verbose output
      run: |
       tar -xvf adressen.tar.xz --to-stdout var/www/PersonalUtils/storage/repos/postcodes/data/adressen.csv > adressen.csv

    - name: List all extracted files
      run: |
        find . -type f

    - name: Compress CSV to tar.gz
      run: |
        tar -czvf adressen.tar.gz adressen.csv

    - name: Generate Timestamp
      id: timestamp
      run: echo "timestamp=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: adressen.tar.gz
        name: CSV Release ${{ steps.timestamp.outputs.timestamp }}
        tag_name: release-${{ steps.timestamp.outputs.timestamp }}
