name: Extract and Release CSV

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  extract-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Pull latest changes from fork (if necessary)
      run: |
        git pull origin main

    - name: List files in repository
      run: |
        pwd
        ls -la

    - name: Debugging tar contents
      run: |
        tar -tvf adressen.tar.xz

    - name: Extract CSV from adressen.tar.xz with verbose output
      run: |
        tar -xvvf adressen.tar.xz

    - name: List all extracted files
      run: |
        find . -type f

    - name: Compress CSV to tar.gz
      run: |
        find . -name "adressen.csv" -exec tar -czvf adressen.tar.gz {} +

    - name: Generate Timestamp
      id: timestamp
      run: echo "timestamp=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: adressen.tar.gz
        name: CSV Release ${{ steps.timestamp.outputs.timestamp }}
        tag_name: release-${{ steps.timestamp.outputs.timestamp }}
